defaults: &defaults
  app_name: Inventory
  noreply: noreply@inventory.heroku.com
  host: localhost:3000
  unit_types: ['Box', 'Monitor']

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: inventory.heroku.com
