defaults: &defaults
  app_name: Inventory
  noreply: noreply@inv.flatsoft.com
  host: localhost:3000
  unit_types: [Box, Monitor, Mouse, Keyboard, Server, Notebook, Webcam, Printer, Network tools, Other]

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  host: inv.flatsoft.com
