defaults_developmet: &defaults_developmet
  adapter: mysql
  encoding: utf8
  host: localhost
  username: root
  password:

development:
  database: inventory_dev
  <<: *defaults_developmet

test:
  database: inventory_test
  <<: *defaults_developmet

cucumber:
  database: inventory_test
  <<: *defaults_developmet